from app.models.device_inventory import (
    DeviceInventoryItem,
    DeviceInventoryMode,
    DeviceInventorySubmission,
    DeviceNetworkPlacement,
    DeviceTrustLevel,
    DeviceType,
    DeviceUpdateStatus,
)


def get_demo_device_inventory_submission() -> DeviceInventorySubmission:
    return DeviceInventorySubmission(
        mode=DeviceInventoryMode.DEMO,
        acknowledged_manual=True,
        user_notes="Demo-only inventory with fake labels. No router login, scan, IP, MAC, or hostname data is used.",
        devices=[
            DeviceInventoryItem(
                id="demo-main-laptop",
                label="Demo Main Laptop",
                device_type=DeviceType.COMPUTER,
                recognized=True,
                trust_level=DeviceTrustLevel.TRUSTED,
                network_placement=DeviceNetworkPlacement.MAIN_NETWORK,
                update_status=DeviceUpdateStatus.UP_TO_DATE,
                used_by="me",
                sensitive=True,
            ),
            DeviceInventoryItem(
                id="demo-family-phone",
                label="Demo Family Phone",
                device_type=DeviceType.PHONE,
                recognized=True,
                trust_level=DeviceTrustLevel.TRUSTED,
                network_placement=DeviceNetworkPlacement.MAIN_NETWORK,
                update_status=DeviceUpdateStatus.NEEDS_REVIEW,
                used_by="family",
                sensitive=True,
            ),
            DeviceInventoryItem(
                id="demo-smart-tv",
                label="Demo Smart TV",
                device_type=DeviceType.SMART_TV,
                recognized=True,
                trust_level=DeviceTrustLevel.LIMITED_TRUST,
                network_placement=DeviceNetworkPlacement.MAIN_NETWORK,
                update_status=DeviceUpdateStatus.UNKNOWN,
                used_by="family",
            ),
            DeviceInventoryItem(
                id="demo-video-doorbell",
                label="Demo Video Doorbell",
                device_type=DeviceType.DOORBELL,
                recognized=True,
                trust_level=DeviceTrustLevel.LIMITED_TRUST,
                network_placement=DeviceNetworkPlacement.MAIN_NETWORK,
                update_status=DeviceUpdateStatus.UNKNOWN,
                used_by="family",
            ),
            DeviceInventoryItem(
                id="demo-guest-device",
                label="Demo Guest Device",
                device_type=DeviceType.GUEST_DEVICE,
                recognized=True,
                trust_level=DeviceTrustLevel.GUEST,
                network_placement=DeviceNetworkPlacement.MAIN_NETWORK,
                update_status=DeviceUpdateStatus.UNKNOWN,
                used_by="guest",
            ),
            DeviceInventoryItem(
                id="demo-unknown-device",
                label="Unknown Demo Device",
                device_type=DeviceType.UNKNOWN,
                recognized=False,
                trust_level=DeviceTrustLevel.UNKNOWN,
                network_placement=DeviceNetworkPlacement.UNKNOWN,
                update_status=DeviceUpdateStatus.UNKNOWN,
                used_by="unknown",
            ),
        ],
    )
